basePath: /api
definitions:
  dtos.ClassScheduleDTO:
    properties:
      capacity:
        type: integer
      end_date:
        type: string
      name:
        type: string
      start_date:
        type: string
    required:
    - capacity
    - end_date
    - name
    - start_date
    type: object
  entities.ClassSchedule:
    properties:
      capacity:
        type: integer
      end_date:
        type: string
      id:
        type: integer
      name:
        type: string
      start_date:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: la_luisalmas@hotmail.com
    name: Luís Almas
  description: A book management service API in Go using Gin framework.
  title: Gym management API
  version: "1.0"
paths:
  /classes:
    get:
      description: Returns all scheduled classes.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entities.ClassSchedule'
            type: array
      summary: Get classes
      tags:
      - classes
    post:
      description: Post a new class.
      parameters:
      - description: ClassScheduleDTO JSON
        in: body
        name: classScheduleDTO
        required: true
        schema:
          $ref: '#/definitions/dtos.ClassScheduleDTO'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/entities.ClassSchedule'
      summary: Post class
      tags:
      - classes
  /classes/{id}:
    get:
      description: Returns single class.
      parameters:
      - description: ClassSchedule Id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entities.ClassSchedule'
      summary: Get class
      tags:
      - classes
    put:
      description: Updates a single class.
      parameters:
      - description: ClassSchedule Id
        in: path
        name: id
        required: true
        type: string
      - description: ClassScheduleDTO JSON
        in: body
        name: classScheduleDTO
        required: true
        schema:
          $ref: '#/definitions/dtos.ClassScheduleDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entities.ClassSchedule'
      summary: Put classes
      tags:
      - classes
swagger: "2.0"
